spring.application.name=sistemas

spring.datasource.url=jdbc:mysql://mysql-2651cbfe-ramiro-labprogramacion.j.aivencloud.com:27578/sistemas_db?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_wUUmIzvnoXKVrj1hTbw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
